
package com.waldomilanes.invoice.viewers;

import com.waldomilanes.invoice.jpacontrollers.Decision;
import com.waldomilanes.invoice.jpacontrollers.ModeloJpaController;
import com.waldomilanes.invoice.pojos.OrdenDetalle;
import com.waldomilanes.invoice.utilities.GeneralMethods;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Instructor
 */
public class DetalleScreen extends javax.swing.JDialog {
    OrdenDetalle detalle;

    public DetalleScreen(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/META-INF/money.png")).getImage());
        setLocationRelativeTo(null);
       
        busqueda(Decision.DETALLES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbHistorial = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        lbDeSeleccionado = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        capturar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 198, 165));
        setForeground(new java.awt.Color(0, 198, 165));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbHistorial.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/history.png"))); // NOI18N
        lbHistorial.setText("HISTORIAL DE DETALLES");

        botonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/select.png"))); // NOI18N
        botonBuscar.setText("Seleccionar");
        botonBuscar.setBorder(null);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        txtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarFocusLost(evt);
            }
        });
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tablaDetalle.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero de orden", "numero de producto", "cantida", "fecha", "costo", "ITBIS"
            }
        ));
        jScrollPane2.setViewportView(tablaDetalle);

        lbDeSeleccionado.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lbDeSeleccionado.setText("DETALLE seleccionado: ");

        borrar.setBackground(new java.awt.Color(255, 255, 255));
        borrar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/if_Erase_132784.png"))); // NOI18N
        borrar.setText("Borrar");
        borrar.setBorder(null);
        borrar.setDoubleBuffered(true);
        borrar.setIconTextGap(1);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        editar.setBackground(new java.awt.Color(255, 255, 255));
        editar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/if_Notes_132689.png"))); // NOI18N
        editar.setText("Editar");
        editar.setBorder(null);
        editar.setDoubleBuffered(true);
        editar.setIconTextGap(1);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        capturar.setBackground(new java.awt.Color(255, 255, 255));
        capturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/return.png"))); // NOI18N
        capturar.setText("Volver a factura");
        capturar.setBorder(null);
        capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/cash1.png"))); // NOI18N
        jLabel4.setText("CASH1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                        .addComponent(capturar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(lbDeSeleccionado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lbHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(lbHistorial)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDeSeleccionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capturar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        //    StringBuffer buffer = new StringBuffer();
        //        for(int i=0;i<3;i++){
            //            buffer.append("   "+jTable1.getColumnName(i)+": ");
            //            buffer.append("   "+jTable1.getValueAt(jTable1.getSelectedRow(), i)+"   ");
            //        }
        //            jTextArea1.setText(buffer.toString());
        //

    }//GEN-LAST:event_jTable1MouseReleased

    private void txtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusGained
        //    jTextField1.setText("");
    }//GEN-LAST:event_txtBuscarFocusGained

    private void txtBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFocusLost
        if(txtBuscar.getText().equalsIgnoreCase("")){
            busqueda(Decision.ALLDETALLE);
        }else{
            
            busqueda(Decision.DETALLEXORDEN,0);
        }
    }//GEN-LAST:event_txtBuscarFocusLost

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        //        jTextField1.setText("");
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        if(tablaDetalle.getValueAt(0, 0)== null){
            JOptionPane.showMessageDialog(this, "Asegurese que tiene un detalle seleccionado.\nVuelva a intentarlo.");
        }else{
            llenar(3);
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        if(tablaDetalle.getValueAt(0, 0)== null){
            JOptionPane.showMessageDialog(this, "Asegurese que tiene un detalle seleccionado.\nVuelva a intentarlo.");
        }else{
            llenar(2);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void capturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarActionPerformed
        dispose();
        new FacturaApp((Frame) this.getParent(), false).setVisible(true);
        
    }//GEN-LAST:event_capturarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String[] ar = new String[6];
        for(int i=0;i< jTable1.getRowCount();i++){

            if(txtBuscar.getText().equalsIgnoreCase(String.valueOf(jTable1.getValueAt(i, 0)))){

                ar[0] = String.valueOf(jTable1.getValueAt(i, 0));
                ar[1] = String.valueOf(jTable1.getValueAt(i, 1));
                ar[2] = String.valueOf(jTable1.getValueAt(i, 2));
                ar[3] = String.valueOf(jTable1.getValueAt(i, 3));
                ar[4] = String.valueOf(jTable1.getValueAt(i, 4));
                ar[5] = String.valueOf(jTable1.getValueAt(i, 5));
            }else{
                try{
                    ar[0] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                    ar[1] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
                    ar[2] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                    ar[3] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3));
                    ar[4] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4));
                    ar[5] = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5));
                    jTable1.setFocusable(false);

                }catch(Exception e){

                }
            }
        }
        DefaultTableModel m = new DefaultTableModel();
        m.addColumn("numero de orden");
        m.addColumn("Referencia");
        m.addColumn("cantidad");
        m.addColumn("precio");
        m.addColumn("costo");
        m.addColumn("ITBIS");
        m.addRow(ar);
        tablaDetalle.setModel(m);
        tablaDetalle.setForeground(Color.WHITE);
        tablaDetalle.setBackground(Color.RED);
    }//GEN-LAST:event_botonBuscarActionPerformed
 public void llenar(int operationType) {
        try {
            if (tablaDetalle.getValueAt(0, 0) != null) {
                detalle = GeneralMethods.OrdenDetalles.ordenDetalleGenerator(Integer.parseInt(String.valueOf(tablaDetalle.getValueAt(0, 0))));              
            }
            if (operationType == 0) {
                dispose();
                new FacturaApp((Frame) this.getParent(),true).setVisible(true);
            } else if (operationType == 2) {
                dispose();
                new Editor(detalle, 1).setVisible(true);
            } else if (operationType == 3) {
                dispose();
                new Editor(detalle, 2).setVisible(true);
            }
        } catch (Exception e) {
            Icon icon = (new javax.swing.ImageIcon(getClass().getResource("/META-INF/asegurese.png")));
            JOptionPane.showConfirmDialog(this, e,
                     "Notificacion", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }
    public void busqueda(Decision SQL) {
        DefaultTableModel m;
        try {
            m = ModeloJpaController.modelAll(SQL);
            jTable1.setModel(m);

        } catch (Exception es) {
            JOptionPane.showMessageDialog(null, es);
        }
    }
    public void busqueda(Decision SQL, int i) {
        DefaultTableModel m;
        try {
            m = ModeloJpaController.modelGenerator(SQL, txtBuscar.getText());
            jTable1.setModel(m);

        } catch (Exception es) {
            JOptionPane.showMessageDialog(null, es);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetalleScreen dialog = new DetalleScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton capturar;
    private javax.swing.JButton editar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDeSeleccionado;
    private javax.swing.JLabel lbHistorial;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
